//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciaTelegrama.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelegramaEntities : DbContext
    {
        public TelegramaEntities()
            : base("name=TelegramaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Outros> Outros { get; set; }
        public virtual DbSet<Rcms> Rcms { get; set; }
        public virtual DbSet<Rdm> Rdm { get; set; }
        public virtual DbSet<Telegrama> Telegrama { get; set; }
    }
}
